# src/superagent/aggregator.py
"""
Aggregator: combine SubtaskResult objects into a final markdown report.

Strategy (MVP):
- Prefer WriterAgent's markdown if present (task type write_report).
- Otherwise, construct a simple markdown from Research/Trends/Insights results.
- Always append a Limitations section (model-based).
"""

from typing import List, Dict, Any
from .plan_schema import SubtaskResult, Plan
import datetime


def aggregate_results(results: List[SubtaskResult], plan: Plan, metadata: Dict[str, Any] = None) -> Dict[str, Any]:
    """
    Returns:
        {
            "markdown": str,
            "sections": {"overview":..., "trends":..., "insights":..., "recommendations": ...},
            "meta": {...}
        }
    """
    metadata = metadata or {}
    # index results by task_id
    by_task = {r.task_id: r for r in results}

    # attempt to use writer's markdown if available (writer task id = t4 by planner)
    writer_res = by_task.get("t4")
    if writer_res and writer_res.success and "markdown" in writer_res.data:
        markdown = writer_res.data["markdown"]
        return {"markdown": markdown, "sections": {}, "meta": metadata}

    # otherwise assemble manually from available parts
    overview = ""
    trends_md = ""
    insights_md = ""
    recommendations_md = ""

    # t1 research overview
    t1 = by_task.get("t1")
    if t1 and t1.success:
        ov = t1.data.get("summary") or t1.data.get("result") or ""
        overview = ov

    # t2 trends
    t2 = by_task.get("t2")
    if t2 and t2.success:
        trends = t2.data.get("trends", [])
        lines = []
        for t in trends:
            title = t.get("title") if isinstance(t, dict) else str(t)
            expl = t.get("explanation", "")
            lines.append(f"- **{title}** — {expl}")
        trends_md = "\n".join(lines)

    # t3 insights
    t3 = by_task.get("t3")
    if t3 and t3.success:
        insights = t3.data.get("insights", [])
        lines = []
        for ins in insights:
            insight_text = ins.get("insight") if isinstance(ins, dict) else str(ins)
            impl = ins.get("implication", "")
            lines.append(f"- **{insight_text}** — {impl}")
        insights_md = "\n".join(lines)

    # simple recommendations derived from insights (mock)
    if t3 and t3.success:
        recommendations_md = "- Consider testing hypothesis A\n- Prioritize experiment B\n"

    # assemble markdown
    topic = metadata.get("topic", "Unknown topic")
    ts = datetime.datetime.utcnow().isoformat() + "Z"
    md_parts = [
        f"# Report: {topic}\n",
        "## Executive Summary\n",
        overview or "(No overview produced)\n",
        "\n## Trends\n",
        trends_md or "- (No trends produced)\n",
        "\n## Insights\n",
        insights_md or "- (No insights produced)\n",
        "\n## Recommendations\n",
        recommendations_md or "- (No recommendations)\n",
        "\n---\n",
        f"_Generated by Agentic Report Swarm (mock) at {ts}_\n",
        "\n### Limitations\n",
        "This report is an automated mock result intended for demo. Replace the mock adapters with real OpenAI adapters to produce real content.\n"
    ]

    markdown = "\n".join(md_parts)
    return {"markdown": markdown, "sections": {"overview": overview, "trends": trends_md, "insights": insights_md, "recommendations": recommendations_md}, "meta": metadata}
